server:
    port: 8082
spring:
    application:
        name: demo
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
logging:
    level:
        com.withyou.services.demo: debug
        org.springframework.security: debug