server:
    port: 8082
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/inceptio?useUnicode=true&characterEncoding=utf-8
        username: root
        password:
    application:
        name: S-DEMO
logging:
    level:
        com.withyou.services.demo: debug
        org.springframework.security: debug

eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
    instance:
        prefer-ip-address: true

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.withyou.services.demo.domain.entity