server:
    port: 8082
spring:
    application:
        name: S-DEMO
logging:
    level:
        com.withyou.services.demo: debug
        org.springframework.security: debug

eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
    instance:
        prefer-ip-address: true