server:
    port: 8081
spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
            -   filters:
                - StripPrefix=0
                id: demo
                predicates:
                -   Path=/test/**
                uri: lb://demo
            -   id: auth
                filters:
                -   StripPrefix=0
                predicates:
                -   Path=/auth/**
                uri: lb://auth

eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
    instance:
        prefer-ip-address: true
