server:
    port: 8081
spring:
    application:
        name: S-GATEWAY
    cloud:
        gateway:
            routes:
            -   filters:
                - StripPrefix=1
                id: S-DEMO
                predicates:
                -   Path=/demo/**
                uri: lb://S-DEMO
            -   id: S-AUTH
                filters:
                -   StripPrefix=1
                predicates:
                -   Path=/auth/**
                uri: lb://S-AUTH

eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
    instance:
        prefer-ip-address: true
