server:
  port: 8083
spring:
  application:
    name: S-AUTH
logging:
  level:
    com.withyou.auth: debug
    org.springframework.security: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true