server:
  port: 8083
spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    com.withyou.auth: debug
    org.springframework.security: debug